"""followers

Revision ID: 77860bb268bc
Revises: b6c19ab94ebf
Create Date: 2019-04-02 13:18:42.754304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77860bb268bc'
down_revision = 'b6c19ab94ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
